<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net11.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\Shared\NovoDwarf.Primitives\NovoDwarf.Primitives.csproj" />
      <ProjectReference Include="..\Procedural.NET.Core\Procedural.NET.Core.csproj" />
      <ProjectReference Include="..\Procedural.NET.Nodes\Procedural.NET.Nodes.csproj" />
    </ItemGroup>

</Project>
